### ISSUE TITLE
Warning Tensorflow:Autograph

### ISSUE THREAD

**Issue by popkowiersma** [kahst/BirdNET-Analyzer#155]
I receive next warning when analyzing sound files using the Setup Windows installation zip files:

WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.

Does this affect the analysis? And can I solve this issue (without knowledge of python)?

best wishes, Popko Wiersma

**Comment by cbalantic** [comment]
I encountered the same warning and am also interested in the answer. My audio files were still processed when I directed the command prompt to use BirdNET-Analyzer.exe, but the GUI produced the following error sequence and then exited. I am running Windows 10, but have IT restrictions that make it difficult to troubleshoot whether the issue is with the GUI or with our restrictions: 

![image](https://github.com/kahst/BirdNET-Analyzer/assets/16154950/e782db1e-fa0b-4a6c-81bc-699da5861942)

**Comment by Josef-Haupt** [comment]
The AutoGraph warning can be ignored.
@cbalantic This error seems to occure if you don't unblock the executable/archive before.
