### ISSUE TITLE
Portuguese labels are in English

### ISSUE THREAD

**Issue by LSMSugai** [kahst/BirdNET-Analyzer#161]
Hi! The commons species portuguese names [pt] seems to be in english: 

https://github.com/kahst/BirdNET-Analyzer/blob/main/labels/V2.4/BirdNET_GLOBAL_6K_V2.4_Labels_pt.txt

**Comment by Josef-Haupt** [comment]
Hi!
I just compared the english labels with the portuguese ones.
Looks like you are correct.
The file was built using the eBird API, and it appears tu be redundant right now.
So we'll probably remove it in the next update until there are atleast some translations.

**Comment by Mattk70** [comment]
@Josef-Haupt, I believe this must be an issue with your label build process. There is no 'pt' locale on eBird, there are variants for pt_PT (Portuguese in Portugal) or pt_BR (Brazilian Portuguese). Because I am nice, I have attached one for each...
[BirdNET_GLOBAL_6K_V2.4_Labels_pt_BR.txt](https://github.com/user-attachments/files/17950726/BirdNET_GLOBAL_6K_V2.4_Labels_pt_BR.txt)
[BirdNET_GLOBAL_6K_V2.4_Labels_pt_PT.txt](https://github.com/user-attachments/files/17950727/BirdNET_GLOBAL_6K_V2.4_Labels_pt_PT.txt)

**Comment by Mattk70** [comment]
For anyone interested in a Portuguese translation of BirdNET, [Chirpity](https://chirpity.mattkirkland.co.uk) offers a Portuguese UI as well as a choice of European and Brazilian Portuguese labels

**Comment by Josef-Haupt** [comment]
@Mattk70 You are right, very nice of you to attach the real translations. Now that I'm looking at it pt seems like a GPT hallucination.
