### ISSUE TITLE
(Bio)acoustic variables in standard configuration

### ISSUE THREAD

**Issue by FilipeBat1sta** [kahst/BirdNET-Analyzer#164]
I am an undergraduate student in biological sciences at UFRJ and have been using the BirdNET-GUI system for my undergraduate research. I trained a model to identify 7 anuran species and will use it to make circadian cycles. During the validation process, I came to the conclusion that I did not pay attention to the sample rate, frequency range and band size that were used for training and identifying the model. The default used in the GUI is: 512 in nfft, 48 kHz and 0 to 24 in the frequency range? If this is not the standard used, is there a way to find out and is there a plan and/or interest in adding this function to the GUI interface?

**Comment by kahst** [comment]
We use a custom neural network layer to do spectrogram computation, and thus the setting we use are fixed with each model version and cannot be adjusted.

Model V2.4 uses the following settings:

- 48 kHz sampling rate (we up- and downsample automatically and can deal with artifacts from lower sampling rates)
- we compute 2 mel spectrograms as input for the convolutional neural network:
  - first one has fmin = 0 Hz and fmax = 3000; nfft = 2048; hop size = 278; 96 mel bins
  - second one has fmin = 500 Hz and fmax = 15 kHz; nfft = 1024; hop size = 280; 96 mel bins
- both spectrograms have a final resolution of 96x511 pixels
- raw audio will be normalized between -1 and 1 before spectrogram conversion

Hope that helps.

**Comment by FilipeBat1sta** [comment]
Thanks!!!!

**Comment by fegue** [comment]
Should we put this information in the README like 'technical details'?
