### ISSUE TITLE
Curious about the differences between current BirdNET-Analyzer 2.1 vs. the BirdNET-Lite model

### ISSUE THREAD

**Issue by JacobGlennAyers** [kahst/BirdNET-Analyzer#20]
Hi there BirdNET team! I have been working to encapsulate the BirdNET-Lite model which can make predictions for ~6000 species around the world to test out its efficacy in automatically segmenting binary bird labels from large datasets. I just saw the deprecation notice on BirdNET-Lite today and was curious what the main differences between the current Analyzer model 2.1 with ~2500 species. I looked over the model version history, but didn't see any reference to the BirdNET-Lite model. 

A quick follow-up question, is there any variation in the vector space for the model inputs? For my use-case, it would be nice to compare these models, assuming that it is as simple as modifying the path to the respective model and everything working seamlessly.

**Comment by JacobGlennAyers** [comment]
I just saw that this is a partial duplicate of: https://github.com/kahst/BirdNET-Analyzer/issues/9

So it seems that this model is using efficentnet, and they are working on building up more and more species and updating the new framework accordingly. There are likely details I am missing. 

I would still be interested in the second block to gauge if there is any variation in the input space between the two models.

**Comment by kahst** [comment]
You're right, we will gradually improve the new model and add more species to it until we reach the 6,000 species mark. That might take a while though :) 

The new model uses a different (and more efficient) architecture, improved training regime and vastly more training data (esp. soundscape data). So in principle, the new model should outperform the BirdNET-Lite version. This time, we split the audio and metadata parts into two models which run consecutively, instead of merging both parts into one model like we did with the old repo. We noticed that merging both parts resulted in unwanted biases that would lead to false detections for non-events, hence the split. Additionally, the metadata model performance was also improved and now matches eBird frequency data almost perfectly.

We kept the interface as consistent as possible and in theory, you should be able to just plug the new model into your old workflow. However, the best performing parameter settings might have changed and you might need to do some optimization first.

Another notable change is that we will actually actively maintain and manage this repo and reply to issues and feature requests :)

**Comment by JacobGlennAyers** [comment]
@kahst Thanks Stefan! Looking forward to trying out the new model. We are currently testing out BirdNET's capacity to automatically convert weakly labeled data to strongly labeled data. I will go ahead and close this issue.
