### ISSUE TITLE
Confidence scores by BirdNet version

### ISSUE THREAD

**Issue by rflachlan** [kahst/BirdNET-Analyzer#202]
We have a very strange result which we can't make sense of. We have taken a manually annotated 10min file of N American bird song, played it back, and re-recorded it with various microphones. Our plan is to use BirdNet's confidence scores to test the microphones. We've used a Confidence threshold of 0.8 throughout and kept all other parameters (lat +long) the same. The same species of birds are recognised in all files.
(1) From version 2.2 to 2.3 and then 2.4, the number identified segments in the *original stimulus file* declines from 37 to 19 to 12.
(2) For a SongMeter micro, the number identifications *increases* slightly, from 19 to 22 to 22. So for version 2.4, the number of segments classified with Confidence >0.8 is substantially higher in the re-recorded file than the original!
(3) For a Sennheiser ME67 shotgun microphone - a much more highly directional microphone - the number of identifications decreases similarly to the original: 29 to 21 to 12.

Our recording was set up to be in a less than perfect environment with reverberation through some leaves, but at a short-ish distance of 7.5m. The recordings from the SongMeter were not bad, but subjectively clearly worse than the originals. The original recording has clear recordings of birds with low reverberation but with some noticeable wind hiss in the background.

My questions are: 
(1) Has the meaning of "confidence" changed in any way between versions to account for the decline in identifications in the original recording?
(2) Are there changes to configuration options that account for this decline in identification?
(3) Is there any obvious explanation for why recordings that are worse in quality have better confidence scores in version 2.4?

The results are so strange it feels that we are doing something very wrong! Any advice welcome, and thanks for your work on this incredible tool.

**Comment by LimitlessGreen** [comment]
My follow-up question on this topic would be:

**Is this model (well-)calibrated?**
My intuition tells me it might not be. However, I can’t seem to find any information about this or other insights related to this model. Is this documented somewhere?

**Comment by kahst** [comment]
Ok, that's a tricky one, and to be honest: We don't know exactly. We did change augmentation during training runs to improve accuracy on a soundscape test data set (omnidirectional recordings). We also added various types of distortions to the training data to emulate diffrent sampling rates and compression artifacts. We never tried to quantify the effect of recording quality and distance on confidence scores, but we do know that there doesn't seem to be a correclation. [Vincent Lostanlen](https://www.lostanlen.com/)'s team did a study on distance sampling with BirdNET and they concluded that it's not possible because confidence scores do not correlate with distance. Despite augmentation, it appears that BirdNET is still very sensitive to changes in recording equipment and pre-processing and that also keeps changing with newer model versions. I guess we need to think a bit more about these things in the future to make it more robust.

**Comment by LimitlessGreen** [comment]
A friend of mine did something "similar". She had to identify different bird species for multiple locations. So, in the initial moment, she logically sorted all recordings per location based on the highest confidence score. However, in the end, it turned out that a high confidence score doesn't necessarily mean that the species is clearly audible in the recording or that it is in the recording at all.

@kahst thank you a lot for this detailed answer :+1:
