### ISSUE TITLE
Dear BirdNet

### ISSUE THREAD

**Issue by brianeg** [kahst/BirdNET-Analyzer#25]
Dear BirdNET
Have you considered being able to save a recording and share it on Facebook?

Yours sincerely
Brian

**Comment by kahst** [comment]
I assume this comment refers to the app, and yes, we have considered that, but sharing a sound file is tricky since some social networks do not accept audio - it would have to be a video at least. Not sure if this feature will be implemented in the near future, but we are working on another version of the app which might have advanced sharing features. Stay tuned!
