### ISSUE TITLE
Taxonomies

### ISSUE THREAD

**Issue by Mattk70** [kahst/BirdNET-Analyzer#282]
Hey guys,

You already told me that you use the 2021 eBird taxonomy (Clements list) . If I try to submit records to eBird using this taxonomy in the Record Format described in [these instructions](https://support.ebird.org/en/support/solutions/articles/48000907878-upload-spreadsheet-data-to-ebird), I get a heap of errors about the names being incorrect.

Is this somehting you can fix, or should I be asking some other folks at the Cornell labs?

**Comment by kahst** [comment]
I suspect that updates to the taxonomy are the cause here. There have been two so far and another one coming up this August. Can you please check if some of the errors you see line up with the changes mentioned [here](https://science.ebird.org/en/use-ebird-data/the-ebird-taxonomy/2023-ebird-taxonomy-update) and [here](https://science.ebird.org/en/use-ebird-data/the-ebird-taxonomy/2022-ebird-taxonomy-update)?

The next model version will use the 2023 taxonomy and should have updated codes and names.

**Comment by Mattk70** [comment]
Thanks Stefan, that does make sense. 

To fess up, the main issue I had was because the my eBird language preferences didn't line up with the language preferences for BirdNET!
