### ISSUE TITLE
Error with BirdNet GUI when including Negative samples folder

### ISSUE THREAD

**Issue by marisol-valverde** [kahst/BirdNET-Analyzer#354]
**Describe the bug**

Using Birdnnet (V2.4 on a PC), when I include a negative samples folder (-"call_name") to train my own classifier (in addition to the other two folders labelled "call_name" and "noise") I get an error and Birdnet does not run. Only when removing such negative samples folder it works. 

**To Reproduce**
For the GUI:
1. Go to 'Train'
2. Click on 'Training data'
3. Scroll down to '1_trainingdata folder (contains the 3 folders: "noise", "call_name" & "-call_name"). Click Ok. Note: only the "call_name" folder name appears under "Classes". Choose the classifier output folder path. 
4. Click "start training" 
5. Only get: "Error"
6. When I repeat all steps above but remove the negative samples folder, the model starts training just fine. 

**Expected behavior**

I expect to obtain my custom classifier under the output_folder. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2

**Additional context**

**Comment by max-mauermann** [comment]
Hi,
This is most likely due to the fact that we dont allow the negative samples in a binary classfication setting (only distinguishing between signal and background). The reasoning behind this is, that negative samples are used to avoid confusion between similar sounding calls.

The CLI should have an appropriate error message, but it seems the GUI does not. 
I will try to put in the message and also update the readme to mention this behaviour.
