### ISSUE TITLE
Embeddings.py appears to outputs species classifications, not embeddings

### ISSUE THREAD

**Issue by Sean1572** [kahst/BirdNET-Analyzer#38]
I'm currently looking into at Birdnet embeddings for clustering via embeddings.py. Someone I was working with noticed the size of the embeddings array (from the embeddings.py output) is the same size as the species list implying embeddings.py is outputting the classifications. 

After playing around it looks like when running embeddings.py,`loadmodel()` in model.py is being called with `class_output=True `instead of `class_output=False`. When manually changing `class_output=False`, embeddings.py outputs an array of size 420 instead of 2434. 

Which is the correct embeddings array?

EDIT: In embeddings.py on line 75, `models.predict()` is called and it returns an array of size 2434 (same size as species list). Changing this to `models.embeddings()` returns the array of size 420.

**Comment by kahst** [comment]
I wonder how I missed that...you're absolutely right, embeddings should have a different output size and 420 is the correct size. I made a mistake with functions calls, instead of calling `e = model.predict(data)` we need to call `e = model.embeddings(data)`. This way, the script will load the model without the classification layer and thus output embeddings instead of class scores. Good catch!
