### ISSUE TITLE
Segments.py can't match audio and result files

### ISSUE THREAD

**Issue by kahst** [kahst/BirdNET-Analyzer#433]
In `segments.py` audio files and result files can't be matched if the audio dir and result dir are different (which we explicitly allow to do) and we don't use combined result files.

In line 92 we say the dictionary entry is:

`data[os.path.join(root, f.rsplit(".", 1)[0])] = {"audio": os.path.join(root, f), "result": ""}`

which contains the full audio file dir tree.

In line 98 the table_key is:

`table_key = os.path.join(root, f.split(".BirdNET.", 1)[0])`

which then contains the result file dir tree and thus cannot be matched with the keys in the `data` dict.

We could remove the full dir trees from the key and only use the filename without the extension as keys in `data`. However, we might have issues when people have duplicate filenames (which they shouldn't but often do).

What do you think?

**Comment by kahst** [comment]
Also, I think we should use the common name instead of the species code for segments folder names:

`species = d[header_mapping["Species Code"]]`

should be

`species = d[header_mapping["Common Name"]]`

when `rtype == "table"`

(we're very inconsistent with that, we use species code, common name and scientific name depending on the result type)

**Comment by max-mauermann** [comment]
i think we could do something like
`table_key = os.path.join(root.strip(apath), f.split(".BirdNET.", 1)[0])` or `.strip(rpath)` respectively.

this should not cause issues with duplicate filenames in different folders, but would require the audio and result folders to be structured identically (although this is what the analysis outputs anyway)

For the segment folder names we could also add this as an option to choose from.

**Comment by KalmiaLatifolia** [comment]
Hi — it looks like this got (mostly) fixed a while ago, but something about the
way I've named my audio and results folders is still tripping it up in
birdnet-analyzer 2.4.0.

My audio folder is:

```
/Volumes/Shift/campaign2_postfire/sedgwick_campaign2_audio_files
```

and my results folder is:

```
/Volumes/Shift/sedgwick_birdnet_col2025_ana20260821
```

with per-site subfolders like `s2lam083_250419` in both. When I run
`segments.py`, the folder names get parsed incorrectly, so instead of two
matching keys I get:

```
audio  key:  083_250419/s2lam083_250419_2025-05-23_11-20
result key:  3_250419/s2lam083_250419_2025-05-23_11-20
```

Both should be `s2lam083_250419/...`. Nothing matches, so I get
`Found 0 audio files with valid result file.` and an exit code of 0 — which
looked at first like there were simply no detections to extract.

I think the cause is this line (`birdnet_analyzer/segments/utils.py`, line 91,
and the matching one at line 98):

```python
table_key = os.path.join(root.strip(apath), f.rsplit(".", 1)[0])
```

`str.strip()` removes any *characters* in the argument from both ends rather
than removing the prefix, so the parent folder's characters eat into the
subfolder name. Because my two parent folders contain different characters, they
get truncated by different amounts — my results folder name contains the digits
0,1,2,5,6,8 but not 3, while my audio folder contains 2 and no other digits, so
`s2lam083_250419` stops at a different place on each side.

Here's a tiny reproduction with simpler names, standard library only:

```python
import os

apath = "/data/audio"        # audio_input
rpath = "/data/results"      # --results
sub, stem = "site01", "rec1"

print(os.path.join(os.path.join(apath, sub).strip(apath), stem))  # site01/rec1
print(os.path.join(os.path.join(rpath, sub).strip(rpath), stem))  # ite01/rec1
```

The `s` disappears on the results side only, because `s` appears in
`/data/results` but not in `/data/audio`.

I think it works for most people because `--results` defaults to `audio_input`,
so both paths are identical and get truncated identically. It only shows up when
the two folders are separate *and* their names happen to use different
characters.

Swapping in `os.path.relpath` seems to fix it:

```python
table_key = os.path.join(os.path.relpath(root, apath), f.rsplit(".", 1)[0])
```

That keeps the relative-subfolder behaviour, so duplicate filenames across
folders are still distinguished.

In the meantime I worked around it by passing both folders through symlinks
whose names are anagrams of each other (`ab` and `ba` in one temp folder) — since
`strip()` only cares about the set of characters, identical sets truncate both
sides the same way and everything matches.
