### ISSUE TITLE
Cannot select input and output directories in GUI desktop application 

### ISSUE THREAD

**Issue by pefapro117** [kahst/BirdNET-Analyzer#455]
When attempting to select audio directory under "Batch analysis", "Segments", or "Review", there is no error or reaction from the GUI. Doesn't open a file path for me to select a directory. 

**To Reproduce**
For the GUI:
1. Go to 'Single analysis' to upload a file 
2. Click on 'Segments' in order to extract the analyzed 3 second segments 
3. Scroll down to 'Select audio directory (recursive)' 
4. No reaction 
For the CLI provide us with the arguments used.

**Expected behavior**
Expect that it opens a file path for me to select my audio directory which allows me to manually verify 3 s segments of analyzed recordings. The auto-ID results are given along with a confidence interval but I cannot vet them. 

Using Windows

**Comment by byrdgyrl** [comment]
I am having a similar problem with my Desktop BirdNET:

When attempting to select audio input directory under "Batch analysis", "Segments", or "Review", a large ERROR message is displayed and it doesn't open a file path for me to select a directory.

**Comment by max-mauermann** [comment]
Hi,
i am assuming your are using the windows installer version.
This may be related to selecting the "install for all users" option when installing the GUI, at least thats where i encounter similar problems.

Reinstalling with the "install for me only" option might already fix this issue. Alternatively starting the gui as administrator might also be a workaround.

More general this may be caused by installing into a directory where you don't have write access, as the GUI uses some files to store settings. So if you changed the default path during installation this might also be related.

I will also see if i can make it more robust to this problem.

**Comment by byrdgyrl** [comment]
Thanks for these potential fixes, I'll give them a try. 

One challenge is the desktop (and BirdNET on it) is used by multiple students to analyze their recordings, so the "install for all users" is really useful for me here. I suppose I can try the reinstall and giving everyone administrator access, but that isn't ideal either.

In the end, would be helpful to know if/when you can make it more robust to this problem.

Thanks for the quick feedback.
