### ISSUE TITLE
List of non-avian species in BirdNET Analyzer

### ISSUE THREAD

**Issue by heteralocha** [kahst/BirdNET-Analyzer#67]
Hello!

Thanks so much for the incredible resource of BirdNET. In addition to birds, my organization is curious about all of the non-avian sound sources BirdNET can now apparently identify (e.g., we now get engine, various amphibians, coyote, etc.). I went into some of the labels files and I know the possible labels are all there, but I was wondering if there is some easy way to find a list specifically of just the non-avian sounds BirdNET Analyzer can label, so I can bring this information to others. Apologies if this is easily accessible already and I'm just missing it! Any direction is much-appreciated.

Thanks

**Comment by DD4WH** [comment]
Please, do not duplicate issues ! . . . :-)  https://github.com/kahst/BirdNET-Analyzer/issues/64#issue-1435088417

This is what I found so far:
engine
noise
siren
human non-vocal
human vocal
human whistle
power tools
gun
fireworks
dog
Canis latrans_Coyote
Canis lupus_Gray Wolf
Gastrophryne carolinensis_Eastern Narrow-mouthed Toad
Gastrophryne olivacea_Great Plains Narrow-mouthed Toad
Incilius valliceps_Gulf Coast Toad
Anaxyrus americanus_American Toad
Anaxyrus canorus_Yosemite Toad
Anaxyrus cognatus_Great Plains Toad
Anaxyrus fowleri_Fowler's Toad
Anaxyrus houstonensis_Houston Toad
Anaxyrus microscaphus_Arizona Toad
Anaxyrus quercicus_Oak Toad
Anaxyrus speciosus_Texas Toad
Anaxyrus terrestris_Southern Toad
Anaxyrus woodhousii_Woodhouse's Toad
Dryophytes andersonii_Pine Barrens Treefrog
Dryophytes arenicolor_Canyon Treefrog
Dryophytes avivoca_Bird-voiced Treefrog
Dryophytes chrysoscelis_Cope's Gray Treefrog
Dryophytes cinereus_Green Treefrog
Dryophytes femoralis_Pine Woods Treefrog
Dryophytes gratiosus_Barking Treefrog
Dryophytes squirellus_Squirrel Treefrog
Dryophytes versicolor_Gray Treefrog
Eleutherodactylus planirostris_Greenhouse Frog
Hyliola regilla_Pacific Chorus Frog
Lithobates catesbeianus_American Bullfrog
Lithobates clamitans_Green Frog
Lithobates palustris_Pickerel Frog
Lithobates sylvaticus_Wood Frog
Pseudacris brimleyi_Brimley's Chorus Frog
Pseudacris clarkii_Spotted Chorus Frog
Pseudacris crucifer_Spring Peeper
Pseudacris feriarum_Upland Chorus Frog
Pseudacris nigrita_Southern Chorus Frog
Pseudacris ocularis_Little Grass Frog
Pseudacris ornata_Ornate Chorus Frog
Pseudacris streckeri_Strecker's Chorus Frog
Pseudacris triseriata_Striped Chorus Frog
Acris crepitans_Northern Cricket Frog
Acris gryllus_Southern Cricket Frog
Eunemobius carolinus_Carolina Ground Cricket
Eunemobius confusus_Confused Ground Cricket
Gryllus assimilis_Gryllus assimilis
Gryllus fultoni_Southern Wood Cricket
Gryllus pennsylvanicus_Fall Field Cricket
Gryllus rubens_Southeastern Field Cricket
Neonemobius cubensis_Cuban Ground Cricket
Oecanthus celerinictus_Fast-calling Tree Cricket
Oecanthus exclamationis_Davis's Tree Cricket
Oecanthus fultoni_Snowy Tree Cricket
Oecanthus nigricornis_Blackhorned Tree Cricket
Oecanthus niveus_Narrow-winged Tree Cricket
Oecanthus pini_Pine Tree Cricket
Oecanthus quadripunctatus_Four-spotted Tree Cricket
Orocharis saltator_Jumping Bush Cricket

Would be nice if everyone could aid in adding to this list so we get a complete list of all non-avian classes in the model! Just reply to this issue and I will add to the list above.

@heteralocha Could you please list all the amphibian/non-avian names you found? Thanks in advance!

**Comment by cbalantic** [comment]
Thank you @DD4WH! Really helpful. Another few non-avian sounds are: 

Alouatta pigra_Mexican Black Howler Monkey
Environmental_Environmental      (I'm not sure what this means though)

**Comment by Mattk70** [comment]
Not quite, I think you're missing one:     Miogryllus saussurei_Miogryllus saussurei

**Comment by Mattk70** [comment]
Another few:

Allonemobius allardi_Allard's Ground Cricket
Allonemobius tinnulus_Tinkling Ground Cricket
Allonemobius walkeri_Walker's Ground Cricket

**Comment by Mattk70** [comment]
The final clutch (that I could find):

    "Conocephalus brevipennis_Short-winged Meadow Katydid",
    "Conocephalus fasciatus_Slender Meadow Katydid",
    "Orchelimum agile_Agile Meadow Katydid",
    "Orchelimum concinnum_Stripe-faced Meadow Katydid",
    "Orchelimum pulchellum_Handsome Meadow Katydid",
    "Pterophylla camellifolia_Common True Katydid",
    "Scudderia curvicauda_Curve-tailed Bush Katydid",
    "Scudderia furcata_Fork-tailed Bush Katydid",
    "Scudderia texensis_Texas Bush Katydid",
"Microcentrum rhombifolium_Greater Angle-wing"
"Sciurus carolinensis_Eastern Gray Squirrel"
"Atlanticus testaceus_Protean Shieldback"

**Comment by kahst** [comment]
Ok, here you go, this should be the complete list:

Acris crepitans_Northern Cricket Frog
Acris gryllus_Southern Cricket Frog
Allonemobius allardi_Allard's Ground Cricket
Allonemobius tinnulus_Tinkling Ground Cricket
Allonemobius walkeri_Walker's Ground Cricket
Alouatta pigra_Mexican Black Howler Monkey
Amblycorypha alexanderi_Clicker Round-winged Katydid
Amblycorypha longinicta_Common Virtuoso Katydid
Amblycorypha oblongifolia_Oblong-winged Katydid
Amblycorypha rotundifolia_Rattler Round-winged Katydid
Anaxipha exigua_Say's Trig
Anaxyrus americanus_American Toad
Anaxyrus canorus_Yosemite Toad
Anaxyrus cognatus_Great Plains Toad
Anaxyrus fowleri_Fowler's Toad
Anaxyrus houstonensis_Houston Toad
Anaxyrus microscaphus_Arizona Toad
Anaxyrus quercicus_Oak Toad
Anaxyrus speciosus_Texas Toad
Anaxyrus terrestris_Southern Toad
Anaxyrus woodhousii_Woodhouse's Toad
Apis mellifera_Honey Bee
Atlanticus testaceus_Protean Shieldback
Canis latrans_Coyote
Canis lupus_Gray Wolf
Conocephalus brevipennis_Short-winged Meadow Katydid
Conocephalus fasciatus_Slender Meadow Katydid
Cyrtoxipha columbiana_Columbian Trig
Dryophytes andersonii_Pine Barrens Treefrog
Dryophytes arenicolor_Canyon Treefrog
Dryophytes avivoca_Bird-voiced Treefrog
Dryophytes chrysoscelis_Cope's Gray Treefrog
Dryophytes cinereus_Green Treefrog
Dryophytes femoralis_Pine Woods Treefrog
Dryophytes gratiosus_Barking Treefrog
Dryophytes squirellus_Squirrel Treefrog
Dryophytes versicolor_Gray Treefrog
Eleutherodactylus planirostris_Greenhouse Frog
Eunemobius carolinus_Carolina Ground Cricket
Eunemobius confusus_Confused Ground Cricket
Gastrophryne carolinensis_Eastern Narrow-mouthed Toad
Gastrophryne olivacea_Great Plains Narrow-mouthed Toad
Gryllus assimilis_Gryllus assimilis
Gryllus fultoni_Southern Wood Cricket
Gryllus pennsylvanicus_Fall Field Cricket
Gryllus rubens_Southeastern Field Cricket
Hyliola regilla_Pacific Chorus Frog
Incilius valliceps_Gulf Coast Toad
Lithobates catesbeianus_American Bullfrog
Lithobates clamitans_Green Frog
Lithobates palustris_Pickerel Frog
Lithobates sylvaticus_Wood Frog
Microcentrum rhombifolium_Greater Angle-wing
Miogryllus saussurei_Miogryllus saussurei
Neoconocephalus bivocatus_False Robust Conehead
Neoconocephalus ensiger_Sword-bearing Conehead
Neoconocephalus retusus_Round-tipped Conehead
Neoconocephalus robustus_Robust Conehead
Neonemobius cubensis_Cuban Ground Cricket
Odocoileus virginianus_White-tailed Deer
Oecanthus celerinictus_Fast-calling Tree Cricket
Oecanthus exclamationis_Davis's Tree Cricket
Oecanthus fultoni_Snowy Tree Cricket
Oecanthus nigricornis_Blackhorned Tree Cricket
Oecanthus niveus_Narrow-winged Tree Cricket
Oecanthus pini_Pine Tree Cricket
Oecanthus quadripunctatus_Four-spotted Tree Cricket
Orchelimum agile_Agile Meadow Katydid
Orchelimum concinnum_Stripe-faced Meadow Katydid
Orchelimum pulchellum_Handsome Meadow Katydid
Orocharis saltator_Jumping Bush Cricket
Phyllopalpus pulchellus_Handsome Trig
Pseudacris brimleyi_Brimley's Chorus Frog
Pseudacris clarkii_Spotted Chorus Frog
Pseudacris crucifer_Spring Peeper
Pseudacris feriarum_Upland Chorus Frog
Pseudacris nigrita_Southern Chorus Frog
Pseudacris ocularis_Little Grass Frog
Pseudacris ornata_Ornate Chorus Frog
Pseudacris streckeri_Strecker's Chorus Frog
Pseudacris triseriata_Striped Chorus Frog
Pterophylla camellifolia_Common True Katydid
Scaphiopus couchii_Couch's Spadefoot
Sciurus carolinensis_Eastern Gray Squirrel
Scudderia curvicauda_Curve-tailed Bush Katydid
Scudderia furcata_Fork-tailed Bush Katydid
Scudderia texensis_Texas Bush Katydid
Spea bombifrons_Plains Spadefoot
Tamias striatus_Eastern Chipmunk
Tamiasciurus hudsonicus_Red Squirrel
Human vocal_Human vocal
Human non-vocal_Human non-vocal
Human whistle_Human whistle
Dog_Dog
Power tools_Power tools
Siren_Siren
Engine_Engine
Gun_Gun
Fireworks_Fireworks
Environmental_Environmental
Noise_Noise

FYI: Environmental includes things like thunder, wind, water, rain and so on. Fireworks are in there because it can sound like gunshots, which was a way to see if that will improve gunshot detection.

**Comment by Deadleaves99** [comment]
Has anyone else encountered an issue with planes going by being labelled barred owls (0.58CI)?  My ARU is set at a site where you can hear the rumble of the planes landing a town over. The noise has also been labeled 'engine' which is what I would've expected. I am not sure if planes have their own sound class or if anyone else has other suggestions to try?  The other suggestions above helped tremendously so thank you for that!
