### ISSUE TITLE
Any plans for updates?

### ISSUE THREAD

**Issue by abfleishman** [kahst/BirdNET-Analyzer#69]
@kahst any chance you are planning to release new versions of this model in the next few months? Seems like you have stopped working on this repo and we are weighing plans for training our own models vs waiting for BirdNET versions with additional species...

**Comment by lagunabravo** [comment]
Yes @abfleishman, there doesn’t appear to be much action in this repo. You seem to be using these models, have you had any success using the 3k protobuf model? I’m stuck with this issue #57

**Comment by kahst** [comment]
Apologies for the delay, I have not been able to maintain the repo for the last few months; not because I don't want to, but because there are so many other things I have to attend to. But we are still working on improving our models, and we are constantly trying to make things faster, smaller and more reliable. Things just happen in parallel and sometimes, training a new model version takes a really long time (and might not even lead to success, and then we have to start over). 

Here is what we are up to at the moment:

- we are collaborating with local field biologists to provide dedicated regional models, which are important for biodiversity monitoring but not necessarily for this repo
- we are collecting, processing and publishing data so that other researchers can train their own models
- we are working on a BirdNET-Tiny version for Espressif and Arduino microcontrollers
- we are working on a 4K species version of BirdNET for this repo which is faster and smaller than previous version but at the same time supports more species
- we are working on a dedicated BirdNET version for BirdWeather - one of the excellent community projects around BirdNET
- we are also working on improving performance for other taxonomic groups (e.g., mammals, insects or amphibians) in BirdNET, which is tricky at times because of the lack of training data
- this year, we are also organizing and hosting another Kaggle competition, which will likely launch in late February

This repo will still be the main resource for any updated models and interfaces, I will try to do a better job of maintaining the repo in the future. I'll try to tackle some of the more pressing issues that people have submitted in the next few days, there should be plenty that probably don't require that much work. 

Thanks for everyone's patience.

**Comment by tgruetzm** [comment]
Thanks for the update and keep up the good work!

**Comment by PeteLawrence** [comment]
I'm very interested in the dedicated integration with BirdWeather as it's something I've been considering implementing myself.  Has any progress been made on this? Did you have any thoughts on how this should be implemented? Would you accept a pull request?
