### ISSUE TITLE
Could not load tflite model

### ISSUE THREAD

**Issue by lsetoreith** [kahst/BirdNET-Analyzer#75]
Hi,

I'm trying to run `analyze.py` but I get an error when trying to load the tflite model.

Here is the error I get:
`  File "C:\Users\(name)\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\lite\python\interpreter.py", line 455, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'C:\Users\(name)\Documents\ENS\M2\stage\BirdNET-Analyzer-main\checkpoints\V2.2\BirdNET_GLOBAL_3K_V2.2_MData_Model_FP16.tflite'.`

What is the problem there? I am on Windows by the way.

**Comment by HGFestl** [comment]
Hi Isetoreith, 
if I use BirdNET on Windows, I run "BirdNET-Analyzer.exe" instead of "analyze.py". And here I only found version "V2.1", not "V2.2". The directory structure is "BirdNET-Analyzer" instead of "BirdNET-Analyzer-main".
So, did you really install the Windows version of BirdNET?
Best regards
