### ISSUE TITLE
Analyse.py running on example but not on my wav files (Ubuntu 22) 

### ISSUE THREAD

**Issue by ChangenetAlex** [kahst/BirdNET-Analyzer#76]
Hello I am trying to run the analyse.py scripts on my audio recordings (around 10 minutes length), put in the example directory for the test but I systematically got the following message: 
"Error: Cannot open audio file example/Myfile.wav" altough it works well on the "soundscape.wav" file. 
I am on Ubuntu 22.04.2 LTS

I suspected it comes from my files but I used the GUI version of BirdNET on a windows machine several weeks ago and it worked well. 

I'll try to use the docker version but would be super happy to get feedback on this issue. 

All the best and thanks for your work !

**Comment by Josef-Haupt** [comment]
Hi! Your issue could be related to same as #78. Could you check if your user has read permissions for your audio recordings?

**Comment by ChangenetAlex** [comment]
Hi. I did suspect this so I had put the permissions to chmod 777 on the files in the folder with no success. I also tried from the docker repository and the same problem arose: work fine on the example file and does not work on my files.

**Comment by Josef-Haupt** [comment]
I see, currently we are not very verbose with the type of error that occured. I'll update the code in the coming days to show the explicit error for the file.

**Comment by Yaniel-Wong** [comment]
I have the same problem as @ChangenetAlex  mentioned. I tried to move wav files into BirdNET folder, but it didn't work. Also the wav can work well on Win11 with GUI verison.

I installed BirdNet in conda because it needs the old version Python(3.9). I'm not sure whether BirdNet(or exactly librosa) can't get access or work well in  conda environment.

So Any suggestion and solution of this problem? I am looking forward to your feedback. Thanks!

**Comment by Yaniel-Wong** [comment]
I have the same problem as @ChangenetAlex  mentioned. I tried to move wav files into BirdNET folder, but it didn't work. Also the wav can work well on Win11 with GUI verison.

I installed BirdNet in conda because it needs the old version Python(3.9). I'm not sure whether BirdNet(or exactly librosa) can't get access or work well in  conda environment.

So Any suggestion and solution of this problem? I am looking forward to your feedback. Thanks!

**Comment by Yaniel-Wong** [comment]
All right  I  probably know what happened and it works well temporarily. BirdNET requires Python 3.8 environment(as readme.md mentions in Windows setup), but codes of setup(Ubuntu) will install the newest Python(3.10) automatically. 
So I suggest the tutor of installation on Linux should highlight the version of Python. Thanks!

![image](https://user-images.githubusercontent.com/89596802/227759688-11075982-a039-4377-856f-83b98628e4d2.png)
