### ISSUE TITLE
Deep Realistic Taxonomic Classifier (Deep-RTC)

### ISSUE THREAD

**Issue by LimitlessGreen** [kahst/BirdNET-Analyzer#82]
Hi,
thank you for this great project 👍
To be honest, I haven't looked into BirdNET very deeply (yet). But are Deep Realistic Taxonomic Classifier (Deep-RTC) a thing?

In simple words: This is a taxonomic "fallback". So if it's uncertain with the species, but certain with the genus. It's taking the genus instead.

I saw it implemented in a (sadly not open) detection system for camera traps, and thought, this could be very beneficial here as well.

**Comment by kahst** [comment]
We thought about this, but I believe it sounds much more compelling than it will actually be. The reason is, birds of the same genus can sound drastically different and birds of different genera can sound very similar. You could chose the family or order as a fallback instead, because an aquatic birds certainly sounds different than a songbird. But then, you would essential fallback to a classification saying "well, I don't know what it is, but it is a bird" which might not be super helpful. Of course, it's hard to quantify these effects and overall it might help to have a taxonomic fallback, but I don't think that it's going to be super effective.
