### ISSUE TITLE
Birdnet using wrong location

### ISSUE THREAD

**Issue by wolebe** [kahst/BirdNET-Analyzer#83]
Hi team,
I use BirdnetPi since a year now and wanted to apply the new model v2.2, before I used the lite version.

Now I have a the following challenge, although I am in Berlin (location has not changed - Latitude:52.4153, Longitude: 13.2749), I only get non European birds proposed and erroneously identified. When I do the "Species List Tester", only non European birds are shown. I compared with a list of a friend who lives close by, for him the correct birds are shown.
![Screenshot 2023-03-20 211601](https://user-images.githubusercontent.com/67017601/226455670-da8982eb-11ff-46ee-a2c3-1b3b2c73e39e.jpg)

I would appreciate your help.
Best regards,

                        -- Wolfram

**Comment by smashery** [comment]
Came across this yesterday too. This looks like a bug in BirdNET-Pi itself, not this analyzer. The labels appear to get out of sync between the two models (i.e. the model classifies it correctly, but the incorrect label is applied when displaying it, because the label file hasn't been correctly updated on disk). I'm still looking into exactly to fix it properly, but in the meantime, if you run `$home/BirdNET-Pi/scripts/install_language_label_nm.sh -l de` (or whatever language code you want - I'm presuming `de` if you're from Germany), it should fix up the labels.

**Comment by wolebe** [comment]
Hi Ashley,Thanks for responding so quickly. I played around a bit more and at some point after changing between the lite model and v2.2 several times it now works. Best regards,    -- WolframOn 21. Mar 2023, at 06:29, Ashley Donaldson ***@***.***> wrote:﻿
Came across this yesterday too. This looks like a bug in BirdNET-Pi itself, not this analyzer. The labels appear to get out of sync between the two models (i.e. the model classifies it correctly, but the incorrect label is applied when displaying it, because the label file hasn't been correctly updated on disk). I'm still looking into exactly to fix it properly, but in the meantime, if you run $home/BirdNET-Pi/scripts/install_language_label_nm.sh -l de (or whatever language code you want - I'm presuming de if you're from Germany), it should fix up the labels.
